/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sendimage.proto */

#ifndef PROTOBUF_C_sendimage_2eproto__INCLUDED
#define PROTOBUF_C_sendimage_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct SendImage SendImage;


/* --- enums --- */


/* --- messages --- */

struct  SendImage
{
  ProtobufCMessage base;
  char *a;
};
#define SEND_IMAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&send_image__descriptor) \
    , NULL }


/* SendImage methods */
void   send_image__init
                     (SendImage         *message);
size_t send_image__get_packed_size
                     (const SendImage   *message);
size_t send_image__pack
                     (const SendImage   *message,
                      uint8_t             *out);
size_t send_image__pack_to_buffer
                     (const SendImage   *message,
                      ProtobufCBuffer     *buffer);
SendImage *
       send_image__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   send_image__free_unpacked
                     (SendImage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SendImage_Closure)
                 (const SendImage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor send_image__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_sendimage_2eproto__INCLUDED */
