/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sendimage.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sendimage.pb-c.h"
void   send_image__init
                     (SendImage         *message)
{
  static const SendImage init_value = SEND_IMAGE__INIT;
  *message = init_value;
}
size_t send_image__get_packed_size
                     (const SendImage *message)
{
  assert(message->base.descriptor == &send_image__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t send_image__pack
                     (const SendImage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &send_image__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t send_image__pack_to_buffer
                     (const SendImage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &send_image__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SendImage *
       send_image__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SendImage *)
     protobuf_c_message_unpack (&send_image__descriptor,
                                allocator, len, data);
}
void   send_image__free_unpacked
                     (SendImage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &send_image__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor send_image__field_descriptors[1] =
{
  {
    "a",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SendImage, a),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned send_image__field_indices_by_name[] = {
  0,   /* field[0] = a */
};
static const ProtobufCIntRange send_image__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor send_image__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sendImage",
  "SendImage",
  "SendImage",
  "",
  sizeof(SendImage),
  1,
  send_image__field_descriptors,
  send_image__field_indices_by_name,
  1,  send_image__number_ranges,
  (ProtobufCMessageInit) send_image__init,
  NULL,NULL,NULL    /* reserved[123] */
};
